# -*- coding: utf-8 -*-
"""RNA_SOM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVjqyY1EE3HeMw-QDvFILRIOg9pYKZL6
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("imakash3011/customer-personality-analysis")

print("Path to dataset files:", path)

import os

# List the contents of the downloaded directory
print(f"Files in {path}:")
for dirname, _, filenames in os.walk(path):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import pandas as pd

# Assuming the main data file is 'marketing_campaign.csv'
# It seems the file is tab-separated, so we specify the delimiter.
df = pd.read_csv(os.path.join(path, 'marketing_campaign.csv'), sep='\t')

print("\nFirst 5 rows of the dataset:")
display(df.head())

print("\nDataset information:")
df.info()

print("\nFirst 5 rows of the dataset:")
display(df.head())

print("Valores faltantes por columna:")
print(df.isnull().sum())

"""### Manejo de valores faltantes

Procederemos a rellenar los valores nulos en la columna 'Income' con la mediana de la columna.
"""

# Calcular la mediana de la columna 'Income'
income_median = df['Income'].median()

# Rellenar los valores faltantes en la columna 'Income' con la mediana calculada
df['Income'].fillna(income_median, inplace=True)

print("\nValores faltantes por columna después de imputar 'Income':")
print(df.isnull().sum())

print("\nInformación del dataset después de manejar los valores faltantes en 'Income':")
df.info()

"""### Análisis de variables numéricas

Comenzaremos con un resumen estadístico de las columnas numéricas para entender su distribución central, dispersión y posibles rangos de valores.
"""

print("\nEstadísticas descriptivas de las variables numéricas:")
display(df.describe())

"""### Normalización de Variables Numéricas

Procederemos a normalizar las variables numéricas para que tengan una media de 0 y una desviación estándar de 1, lo que ayuda a que los algoritmos de aprendizaje automático funcionen de manera más eficiente.
"""

from sklearn.preprocessing import StandardScaler
import pandas as pd

# Identificar columnas numéricas para normalizar.
# Excluiremos 'ID' porque es un identificador y 'Z_CostContact', 'Z_Revenue' porque son constantes.
numerical_cols_to_normalize = ['Year_Birth', 'Income', 'Kidhome', 'Teenhome', 'Recency',
                               'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds',
                               'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth']

# Inicializar el StandardScaler
scaler = StandardScaler()

# Aplicar la normalización a las columnas seleccionadas
df[numerical_cols_to_normalize] = scaler.fit_transform(df[numerical_cols_to_normalize])

print("\nPrimeras 5 filas del dataset después de la normalización:")
display(df.head())

print("\nEstadísticas descriptivas de las variables numéricas normalizadas:")
display(df[numerical_cols_to_normalize].describe())

"""### Análisis de variables categóricas

Procederemos a examinar las variables categóricas para entender la distribución de sus categorías y si hay alguna desproporción o patrón interesante.
"""

# Seleccionar columnas categóricas
categorical_cols = df.select_dtypes(include='object').columns

print("\nValores únicos y su conteo para variables categóricas:")
for col in categorical_cols:
    print(f"\nColumna: {col}")
    print(df[col].value_counts())
    print("---------------------")

"""Ahora, visualicemos la distribución de estas variables categóricas para una mejor comprensión."""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 10))
for i, col in enumerate(categorical_cols):
    plt.subplot(2, 2, i + 1) # Ajustar el tamaño de la cuadrícula según el número de columnas categóricas
    sns.countplot(data=df, x=col, palette='viridis')
    plt.title(f'Distribución de {col}')
    plt.xlabel('')
    plt.ylabel('Conteo')
    plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""### Codificación One-Hot de la variable 'Education'

Para preparar la variable categórica 'Education' para el modelado, utilizaremos One-Hot Encoding. Esta técnica crea nuevas columnas binarias (0 o 1) para cada categoría única en la columna 'Education', lo que permite que los algoritmos interpreten estos datos sin asumir una relación ordinal incorrecta.

Después de la codificación, eliminaremos la columna original 'Education' para evitar la redundancia y problemas de multicolinealidad.
"""

df = pd.get_dummies(df, columns=['Education'], prefix='Education', drop_first=False)

print("Primeras 5 filas del dataset después de codificar 'Education':")
display(df.head())

print("Columnas del dataset después de codificar 'Education':")
print(df.columns)

"""### Codificación One-Hot de la variable 'Marital_Status'

Continuando con la preparación de los datos para el modelado, aplicaremos One-Hot Encoding a la variable categórica 'Marital_Status'. Esta técnica convertirá las categorías de estado civil en columnas binarias, lo que permitirá a los algoritmos procesar esta información de manera efectiva.
"""

df = pd.get_dummies(df, columns=['Marital_Status'], prefix='Marital_Status', drop_first=False)

print("Primeras 5 filas del dataset después de codificar 'Marital_Status':")
display(df.head())

print("Columnas del dataset después de codificar 'Marital_Status':")
print(df.columns)

"""### Aplicación de Self-Organizing Maps (SOM)

Ahora que los datos están preprocesados, aplicaremos los Self-Organizing Maps (SOM), una técnica de red neuronal no supervisada, para la segmentación de clientes. Los SOM son útiles para reducir la dimensionalidad y visualizar estructuras de clústeres en datos complejos. Nos permitirán identificar grupos de clientes con características de personalidad similares.

Para ello, seleccionaremos las columnas numéricas normalizadas y las columnas categóricas codificadas (Education y Marital_Status), excluyendo las columnas de identificación, fecha y aquellas que son constantes o que no aportan valor para el clustering de personalidad.
"""

!pip install minisom

from minisom import MiniSom
import numpy as np

# Seleccionar las columnas para el entrenamiento del SOM
# Excluimos 'ID', 'Dt_Customer', 'Z_CostContact', 'Z_Revenue', 'Response', 'Customer_Year', 'Customer_Month'
# Las columnas 'Education' y 'Marital_Status' ya han sido one-hot encoded.

som_features = df.drop(columns=[
    'ID',
    'Dt_Customer',
    'Z_CostContact',
    'Z_Revenue',
    'Response'
]).values

# Convertir las características a tipo flotante para evitar errores con minisom
som_features = som_features.astype(float)

# Inicializar y entrenar el SOM
# x, y son las dimensiones del mapa, input_len es el número de características (columnas)
# sigma es el radio inicial de vecindad, learning_rate es la tasa de aprendizaje inicial
# random_seed para reproducibilidad
som_grid_rows = 10
som_grid_cols = 10
input_len = som_features.shape[1]

som = MiniSom(x=som_grid_rows, y=som_grid_cols, input_len=input_len,
              sigma=1.0, learning_rate=0.5, random_seed=42)

som.random_weights_init(som_features)
print("Entrenando el SOM...")
som.train_random(data=som_features, num_iteration=1000)
print("Entrenamiento del SOM completado.")

"""### Análisis de Correlación de las Características del SOM

Para entender las relaciones entre las características utilizadas para entrenar el SOM, visualizaremos la matriz de correlación. Esto nos permitirá identificar características altamente correlacionadas, que podrían ser redundantes, o entender cómo se agrupan ciertos tipos de información.

### Visualización de la U-matrix del SOM

La U-matrix (Unified Distance Matrix) es una técnica de visualización común para los SOM. Muestra la distancia euclidiana promedio entre el vector de peso de una neurona y el de sus neuronas vecinas. Las áreas oscuras indican neuronas que están muy cerca entre sí en el espacio de entrada, lo que sugiere un clúster, mientras que las áreas claras representan límites entre clústeres.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(som_grid_cols, som_grid_rows)) # Use som_grid_cols for width and som_grid_rows for height
plt.pcolor(som.distance_map().T, cmap='bone_r') # U-matrix
plt.colorbar()



plt.title('U-matrix del Self-Organizing Map')
plt.xticks([])
plt.yticks([])
plt.show()

"""### Mapas de Componentes (Component Planes)

Los mapas de componentes visualizan el peso de cada característica de entrada en cada neurona del SOM. Esto ayuda a entender qué características son más prominentes en diferentes regiones del mapa, revelando patrones y características distintivas de los clústeres. Las áreas claras indican valores altos de la característica, mientras que las oscuras indican valores bajos.
"""

# Obtener los nombres de las columnas que se usaron para entrenar el SOM
som_feature_names = df.drop(columns=[
    'ID',
    'Dt_Customer',
    'Z_CostContact',
    'Z_Revenue',
    'Response'
]).columns

# Seleccionar las características clave para visualizar
selected_features = ['Income', 'MntWines', 'Kidhome', 'Education_Graduation', 'Marital_Status_Married']

plt.figure(figsize=(15, 12))

for i, feature_name in enumerate(selected_features):
    # Encontrar el índice de la característica en el array de som_features
    feature_idx = som_feature_names.get_loc(feature_name)

    plt.subplot(3, 2, i + 1) # Ajustar el tamaño de la cuadrícula según el número de características
    plt.title(f'Component Plane for {feature_name}')
    plt.pcolor(som.get_weights()[:, :, feature_idx].T, cmap='viridis')
    plt.colorbar()
    plt.xticks([])
    plt.yticks([])

plt.tight_layout()
plt.show()

"""### Identificación y Visualización de Clústeres en el SOM

Para identificar los clústeres, aplicaremos un algoritmo de clustering (K-Means) a los pesos de las neuronas del SOM. Esto nos permitirá agrupar neuronas similares en el mapa en clústeres. Luego, cada punto de datos del conjunto original será asignado al clúster de su neurona ganadora (BMU), permitiéndonos visualizar la segmentación de clientes.
"""

from sklearn.cluster import MiniBatchKMeans # Usamos MiniBatchKMeans por eficiencia, aunque KMeans también serviría

# Determinar los clústeres en los pesos del SOM
# Ajustamos el número de clústeres basado en la inspección visual de la U-matrix o conocimiento del dominio
n_clusters = 6 # Ejemplo, se puede ajustar

# Obtenemos los pesos de las neuronas del SOM
som_weights = som.get_weights().reshape(-1, input_len)

kmeans = MiniBatchKMeans(n_clusters=n_clusters, random_state=42, n_init='auto')
kmeans.fit(som_weights)

# Asignar cada neurona del SOM a un clúster
som_clusters = kmeans.predict(som_weights).reshape(som_grid_rows, som_grid_cols)

# Asignar cada punto de datos original a un clúster basado en su BMU
cluster_map = np.zeros(som_features.shape[0])
for i, x in enumerate(som_features):
    w = som.winner(x) # BMU para el punto de datos x
    cluster_map[i] = som_clusters[w[0], w[1]]

# Añadir la columna de clústeres al DataFrame original
df['Cluster'] = cluster_map.astype(int)

print("Conteo de clientes por clúster:")
print(df['Cluster'].value_counts())

"""### Visualización de los Clústeres en el SOM

Ahora visualizaremos la U-matrix nuevamente, pero esta vez superpondremos los límites de los clústeres identificados y los puntos de datos, codificados por color según su clúster asignado. Esto nos dará una representación clara de la segmentación de clientes.
"""

plt.figure(figsize=(som_grid_cols, som_grid_rows))
plt.pcolor(som.distance_map().T, cmap='bone_r') # U-matrix de fondo
plt.colorbar()

# Visualizar los límites de los clústeres en el SOM
# Cada color representa un clúster diferente en el mapa
for i in range(som_grid_rows):
    for j in range(som_grid_cols):
        plt.text(j + 0.5, i + 0.5, str(som_clusters[i, j]),
                 ha='center', va='center', bbox=dict(facecolor='white', alpha=0.5, lw=0))

# Opcional: superponer los BMU de los datos originales, coloreados por su clúster
# Esto puede ser denso si hay muchos puntos de datos, pero es útil para ver la distribución
for i, x in enumerate(som_features):
    w = som.winner(x)
    plt.plot(w[0] + 0.5, w[1] + 0.5, 'o', markerfacecolor=plt.cm.Paired(cluster_map[i] / n_clusters),
             markeredgecolor='None', markersize=3, alpha=0.7)

plt.title('SOM con Clústeres Identificados y Puntos de Datos (BMU)')
plt.xticks([])
plt.yticks([])
plt.show()

# Visualización de las características promedio por clúster (ejemplo)
# Agrupamos el DataFrame original por la columna de clúster
cluster_summary = df.groupby('Cluster')[numerical_cols_to_normalize + ['Education_Graduation', 'Marital_Status_Married']].mean()
print("\nCaracterísticas promedio por clúster (variables clave):")
display(cluster_summary)

"""### Detección de Anomalías (Clientes fuera de perfil)

Una forma efectiva de detectar anomalías (outliers) en un contexto de SOM es utilizando la **distancia de cuantificación (quantization error)**. Esta métrica representa la distancia euclidiana entre un vector de entrada (cliente) y el vector de peso de su neurona ganadora (BMU) en el SOM. Un valor alto de distancia de cuantificación indica que el punto de datos está 'lejos' de cualquier neurona del mapa, sugiriendo que podría ser una anomalía o un punto fuera de los patrones principales de los clústeres.
"""

# Calcular la distancia de cuantificación para cada punto de datos individualmente
quantization_errors = np.array([np.linalg.norm(x - som.get_weights()[som.winner(x)]) for x in som_features])

# Añadir la distancia de cuantificación al DataFrame
df['Quantization_Error'] = quantization_errors

# Visualizar la distribución de los errores de cuantificación
plt.figure(figsize=(10, 6))
sns.histplot(df['Quantization_Error'], bins=50, kde=True)
plt.title('Distribución de los Errores de Cuantificación')
plt.xlabel('Error de Cuantificación')
plt.ylabel('Frecuencia')
plt.show()

print("Estadísticas descriptivas de los errores de cuantificación:")
display(df['Quantization_Error'].describe())

"""### Identificación de Anomalías mediante un Umbral

Para identificar las anomalías, estableceremos un umbral basado en la distribución de los errores de cuantificación. Una estrategia común es usar un percentil alto (por ejemplo, el 95º o 99º percentil) como umbral. Los puntos de datos con un error de cuantificación superior a este umbral serán marcados como anomalías.
"""

# Definir un umbral para identificar anomalías (e.g., 99º percentil)
threshold = df['Quantization_Error'].quantile(0.99)

anomalies = df[df['Quantization_Error'] > threshold]

print(f"Umbral de error de cuantificación (99º percentil): {threshold:.4f}")
print(f"Número de anomalías detectadas: {len(anomalies)}")

print("\nPrimeras 5 anomalías detectadas (clientes con mayor error de cuantificación):")
display(anomalies.sort_values(by='Quantization_Error', ascending=False).head())

"""### Visualización de Anomalías en el SOM

Podemos visualizar estas anomalías en el mismo SOM para ver dónde se localizan en relación con los clústeres principales.
"""

plt.figure(figsize=(som_grid_cols, som_grid_rows))
plt.pcolor(som.distance_map().T, cmap='bone_r') # U-matrix de fondo
plt.colorbar()

# Superponer los límites de los clústeres
for i in range(som_grid_rows):
    for j in range(som_grid_cols):
        plt.text(j + 0.5, i + 0.5, str(som_clusters[i, j]),
                 ha='center', va='center', bbox=dict(facecolor='white', alpha=0.5, lw=0))

# Superponer las anomalías
for i, x in anomalies.iterrows():
    # Encontrar la BMU para el punto de datos anómalo
    w = som.winner(som_features[i])
    plt.plot(w[0] + 0.5, w[1] + 0.5, 'x', markerfacecolor='red',
             markeredgecolor='red', markersize=10, markeredgewidth=2, label='Anomalía' if i == anomalies.index[0] else "")

plt.title('SOM con Anomalías Resaltadas')
plt.xticks([])
plt.yticks([])
plt.legend(['Anomalía'], loc='upper right') # Mostrar leyenda solo una vez
plt.show()

"""### Análisis Detallado de las Anomalías

Para entender mejor a los clientes identificados como anomalías, compararemos sus características promedio con las características promedio del dataset completo. Esto nos ayudará a identificar qué atributos son particularmente diferentes en este grupo.
"""

import numpy as np

# Asegurarse de que 'Quantization_Error' esté en df, re-calculándolo si es necesario
if 'Quantization_Error' not in df.columns:
    # Este bloque asume que som y som_features están disponibles de celdas anteriores.
    quantization_errors = np.array([np.linalg.norm(x - som.get_weights()[som.winner(x)]) for x in som_features])
    df['Quantization_Error'] = quantization_errors

# Redefinir 'anomalies' para asegurar que esté disponible
threshold = df['Quantization_Error'].quantile(0.99)
anomalies = df[df['Quantization_Error'] > threshold]

# Obtener las características usadas para el SOM
som_feature_names = df.drop(columns=[
    'ID',
    'Dt_Customer',
    'Z_CostContact',
    'Z_Revenue',
    'Response',
    'Cluster' # 'Cluster' es la única columna adicional en df que no era parte de som_features
]).columns

# Calcular las medias de las características para las anomalías
anomaly_mean = anomalies[som_feature_names].mean()

# Calcular las medias de las características para todo el dataset
overall_mean = df[som_feature_names].mean()

# Unir ambas series en un DataFrame para comparación
comparison_df = pd.DataFrame({
    'Anomalías_Media': anomaly_mean,
    'Dataset_Completo_Media': overall_mean
})

# Calcular la diferencia porcentual para resaltar las mayores desviaciones
comparison_df['Diferencia_Porcentual'] = ((comparison_df['Anomalías_Media'] - comparison_df['Dataset_Completo_Media']) / comparison_df['Dataset_Completo_Media']) * 100

print("Comparación de características promedio: Anomalías vs. Dataset Completo")
display(comparison_df.sort_values(by='Diferencia_Porcentual', ascending=False))

"""## Informe Ejecutivo: Detección de Anomalías

### 1. Introducción

Este informe detalla los resultados del proceso de detección de anomalías dentro de la base de clientes, utilizando los Self-Organizing Maps (SOMs). La identificación de anomalías es crucial para pinpointing clientes con comportamientos atípicos que pueden requerir atención especial, ya sea por ser clientes de alto valor no reconocidos, clientes insatisfechos o incluso indicativos de datos erróneos.

### 2. Metodología

La detección de anomalías se realizó utilizando el **error de cuantificación** (`Quantization_Error`) calculado por el SOM. El error de cuantificación mide la distancia entre cada punto de datos (cliente) y el vector de peso de su neurona ganadora (BMU). Un error alto indica que un cliente está lejos de cualquier patrón de clúster establecido por el SOM. Se estableció un umbral basado en el **99º percentil** del error de cuantificación; aquellos clientes cuyo error superó este umbral fueron clasificados como anomalías.

### 3. Hallazgos Clave

*   **Número de Anomalías Detectadas:** Se identificaron **23 clientes** como anomalías, lo que representa aproximadamente el 1% de la base de datos total.
*   **Características Distintivas de las Anomalías:** Al comparar las características promedio de las anomalías con el promedio general del dataset, se observaron desviaciones significativas en varios atributos clave:
    *   **Mayor Gasto en Categorías Específicas:** Las anomalías muestran un gasto considerablemente más alto en `NumCatalogPurchases` (compras por catálogo), `MntMeatProducts` (productos cárnicos) y `MntGoldProds` (productos de oro).
    *   **Menor Gasto en Tienda:** En contraste, estas anomalías presentan un `NumStorePurchases` (compras en tienda) significativamente menor.
    *   **Perfiles Demográficos Atípicos:** Se observan diferencias notables en la presencia de `Teenhome` (adolescentes en el hogar) y `Kidhome` (niños pequeños en el hogar), así como en `Year_Birth` (edad) y `Recency` (días desde la última compra).
    *   **Educación y Estado Civil:** Existe una mayor proporción de clientes con `Education_PhD` y `Marital_Status_Together` entre las anomalías.

### 4. Visualización de Anomalías

La visualización de las anomalías sobre la U-matrix del SOM reveló que estos puntos atípicos se distribuyen en áreas menos densas del mapa, a menudo en los bordes de los clústeres o en regiones intermedias, lo que refuerza su clasificación como clientes que no encajan claramente en ninguno de los segmentos principales.

### 5. Implicaciones y Recomendaciones

La identificación de estas anomalías ofrece varias oportunidades estratégicas:

*   **Investigación Individualizada:** Cada cliente anómalo debe ser investigado individualmente. Podrían ser:
    *   **Clientes de Nicho:** Clientes con necesidades o preferencias muy específicas que no están cubiertas por los segmentos generales.
    *   **Clientes de Alto Riesgo/Insatisfechos:** Individuos que están a punto de darse de baja o que tienen problemas específicos con el servicio.
    *   **Errores en Datos:** La posibilidad de errores de entrada de datos que distorsionan su perfil.

*   **Estrategias Personalizadas:** Para los clientes anómalos que representan oportunidades de negocio (por ejemplo, clientes de alto gasto en nichos específicos), se pueden diseñar campañas de marketing o productos altamente personalizados.

*   **Mejora del Servicio:** Si las anomalías indican insatisfacción o problemas, el contacto proactivo puede mejorar la retención y la lealtad.

*   **Refinamiento del Modelo:** La comprensión de las anomalías puede llevar a un refinamiento futuro del modelo de segmentación, quizás incorporando nuevas variables o ajustando los parámetros para capturar estos patrones de manera más efectiva.

En conclusión, el análisis de anomalías es una herramienta poderosa que complementa la segmentación de clientes, permitiendo a la empresa identificar y responder a comportamientos inusuales, optimizando así las estrategias de relación con el cliente y la toma de decisiones.

### Compresión de Clientes en Coordenadas (Coordenadas del BMU)

Para 'comprimir a los clientes en coordenadas', asignaremos a cada cliente la posición bidimensional (x, y) de su Neurona Ganadora (BMU - Best Matching Unit) en la cuadrícula del SOM. Estas coordenadas representan una versión de menor dimensionalidad de las características de cada cliente, útil para visualización y análisis posteriores.
"""

# Calcular las coordenadas (x, y) de la BMU para cada punto de datos
bmu_coordinates = np.array([som.winner(x) for x in som_features])

# Añadir las coordenadas del BMU al DataFrame
df['BMU_x'] = bmu_coordinates[:, 0]
df['BMU_y'] = bmu_coordinates[:, 1]

print("Primeras 5 filas del DataFrame con las coordenadas BMU añadidas:")
display(df[['ID', 'BMU_x', 'BMU_y', 'Cluster', 'Quantization_Error']].head())

"""### Segmentos de Clientes Identificados

Basándonos en el análisis de Self-Organizing Maps (SOM) y la aplicación de K-Means a los pesos del SOM, hemos identificado 6 segmentos de clientes distintos. La descripción de cada clúster se basa en sus características promedio (valores normalizados: positivos indican por encima del promedio, negativos por debajo, y cercanos a cero al promedio):

**Clúster 0 (402 clientes): Familias con Adolescentes y Buenos Ingresos**
*   **Edad:** Ligeramente más jóvenes.
*   **Ingresos:** Por encima del promedio.
*   **Hogares:** Menos niños pequeños, más adolescentes.
*   **Gasto:** Promedio o ligeramente por encima en la mayoría de las categorías.
*   **Perfil:** Padres con hijos adolescentes, ingresos estables y consumo moderado.

**Clúster 1 (417 clientes): Familias Jóvenes con Bajo Presupuesto**
*   **Edad:** Ligeramente más jóvenes.
*   **Ingresos:** Por debajo del promedio.
*   **Hogares:** Alta presencia de niños pequeños y adolescentes.
*   **Gasto:** Bajo en todas las categorías de productos.
*   **Perfil:** Familias jóvenes con muchos dependientes y recursos limitados.

**Clúster 2 (284 clientes): Clientes de Alto Valor y sin Dependientes**
*   **Edad:** Mayores que el promedio.
*   **Ingresos:** Significativamente por encima del promedio.
*   **Hogares:** Pocos o ningún niño o adolescente.
*   **Gasto:** Muy alto en todas las categorías de productos.
*   **Perfil:** Segmento de alto valor, clientes mayores con ingresos muy altos y sin dependientes.

**Clúster 3 (671 clientes): Familias Mayores Sensibles al Precio**
*   **Edad:** Mayores que el promedio.
*   **Ingresos:** Significativamente por debajo del promedio.
*   **Hogares:** Presencia de niños pequeños, menos adolescentes.
*   **Gasto:** Muy bajo en todas las categorías, mayor tendencia a ofertas.
*   **Perfil:** Clientes mayores con bajos ingresos y niños pequeños, muy sensibles a los precios.

**Clúster 4 (296 clientes): Jóvenes con Altos Ingresos y Consumo Elegante**
*   **Edad:** Ligeramente más jóvenes.
*   **Ingresos:** Significativamente por encima del promedio.
*   **Hogares:** Pocos o ningún niño o adolescente.
*   **Gasto:** Alto en todas las categorías. Menos visitas a la web.
*   **Perfil:** Clientes jóvenes con altos ingresos y sin dependientes, alto gasto, posiblemente prefieren canales de compra físicos.

**Clúster 5 (170 clientes): Mayores con Niños Pequeños y Bajos Ingresos**
*   **Edad:** Muy mayores (el grupo de mayor edad).
*   **Ingresos:** Por debajo del promedio.
*   **Hogares:** Alta presencia de niños pequeños, menos adolescentes.
*   **Gasto:** Bajo en la mayoría de los productos.
*   **Perfil:** Clientes de edad avanzada, con ingresos por debajo del promedio y niños pequeños en casa, con un gasto general bajo.

### Gasto Promedio por Clúster en Categorías de Productos Clave

Vamos a visualizar el gasto promedio (normalizado) por clúster en algunas categorías de productos clave como Vinos (`MntWines`), Carnes (`MntMeatProducts`), Frutas (`MntFruits`) y Productos Gold (`MntGoldProds`). Esto nos ayudará a entender mejor los perfiles de consumo de cada segmento.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Seleccionar las columnas de gasto para visualizar
spending_cols = ['MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']

# Filtrar el cluster_summary para incluir solo las columnas de gasto
cluster_spending_summary = cluster_summary[spending_cols]

# Reorganizar los datos para facilitar la visualización con seaborn.melt
cluster_spending_melted = cluster_spending_summary.reset_index().melt(id_vars='Cluster', var_name='Product_Category', value_name='Average_Spending_Normalized')

plt.figure(figsize=(14, 8))
sns.barplot(data=cluster_spending_melted, x='Product_Category', y='Average_Spending_Normalized', hue='Cluster', palette='viridis')
plt.title('Gasto Promedio (Normalizado) por Clúster y Categoría de Producto')
plt.xlabel('Categoría de Producto')
plt.ylabel('Gasto Promedio (Normalizado)')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Clúster')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""El gráfico de barras que compara el gasto promedio (normalizado) por clúster en diferentes categorías de productos nos ha permitido observar patrones de consumo muy interesantes:

*   **Clúster 2 y Clúster 4 (Clientes de Alto Valor)**: Estos clústeres muestran un gasto significativamente por encima del promedio en casi todas las categorías de productos, especialmente en vinos y productos cárnicos. Esto refuerza su identificación como segmentos de alto valor, aunque con diferencias en otros aspectos de su perfil (edad, uso de canales de compra).
*   **Clúster 1 y Clúster 3 (Familias con Bajo Presupuesto y Mayores Sensibles al Precio)**: Consistentemente, estos clústeres muestran un gasto por debajo del promedio en todas las categorías. Esto valida su descripción como segmentos con recursos limitados o muy sensibles al precio, lo que se traduce en un consumo más contenido.
*   **Clúster 0 (Familias con Adolescentes y Buenos Ingresos)**: Presentan un gasto ligeramente por encima del promedio en vinos, pero más cercano al promedio o por debajo en otras categorías. Esto indica un consumo más moderado y posiblemente más selectivo en comparación con los clústeres de alto gasto.
*   **Clúster 5 (Mayores con Niños Pequeños y Bajos Ingresos)**: Similar a los clústeres de bajo presupuesto, este grupo muestra un gasto generalizado por debajo del promedio en la mayoría de las categorías, lo cual es coherente con sus ingresos más bajos y la presencia de niños pequeños.

Este gráfico nos proporciona una visión clara y concisa de las diferencias en los hábitos de consumo de cada segmento, lo cual es una información fundamental para diseñar estrategias de marketing personalizadas, optimizar ofertas de productos y asignar recursos de manera más eficiente para cada grupo de clientes.

El gráfico de barras que compara el gasto promedio (normalizado) por clúster en diferentes categorías de productos nos ha permitido observar patrones de consumo muy interesantes:

*   **Clústeres de Alto Valor (Clúster 2 y 4)**: Estos clústeres muestran un gasto significativamente por encima del promedio en casi todas las categorías de productos, especialmente en vinos y productos cárnicos. Esto refuerza su identificación como segmentos de alto valor, aunque con diferencias en otros aspectos de su perfil (edad, uso de canales de compra).
*   **Clúster 1 y Clúster 3 (Familias con Bajo Presupuesto y Mayores Sensibles al Precio)**: Consistentemente, estos clústeres muestran un gasto por debajo del promedio en todas las categorías. Esto valida su descripción como segmentos con recursos limitados o muy sensibles al precio, lo que se traduce en un consumo más contenido.
*   **Clúster 0 (Familias con Adolescentes y Buenos Ingresos)**: Presentan un gasto ligeramente por encima del promedio en vinos, pero más cercano al promedio o por debajo en otras categorías. Esto indica un consumo más moderado y posiblemente más selectivo en comparación con los clústeres de alto gasto.
*   **Clúster 5 (Mayores con Niños Pequeños y Bajos Ingresos)**: Similar a los clústeres de bajo presupuesto, este grupo muestra un gasto generalizado por debajo del promedio en la mayoría de las categorías, lo cual es coherente con sus ingresos más bajos y la presencia de niños pequeños.

Este gráfico nos proporciona una visión clara y concisa de las diferencias en los hábitos de consumo de cada segmento, lo cual es una información fundamental para diseñar estrategias de marketing personalizadas, optimizar ofertas de productos y asignar recursos de manera más eficiente para cada grupo de clientes.

### Aplicaciones de la Segmentación en Marketing y Prevención de Fuga de Clientes

Esta segmentación de clientes es una herramienta extremadamente valiosa para diseñar estrategias de marketing más efectivas y para implementar acciones proactivas de prevención de fuga (churn prevention). Aquí se detallan algunas aplicaciones:

**1. Campañas de Marketing Personalizadas:**

*   **Clústeres de Alto Valor (Clúster 2 y 4):**
    *   **Marketing:** Dirigir campañas con productos premium, ofertas exclusivas y programas de lealtad VIP. Para el Clúster 4, que muestra menos actividad web, se podría priorizar el marketing directo, catálogos físicos o eventos.
    *   **Mensaje:** Destacar la exclusividad, calidad y el estatus. Ej: "Descubra nuestra nueva colección de vinos de edición limitada, seleccionada solo para usted."

*   **Clústeres con Bajo Presupuesto o Sensibles al Precio (Clúster 1, 3 y 5):**
    *   **Marketing:** Concentrarse en promociones de descuento, paquetes de valor, productos de marca blanca o más económicos. Promocionar ofertas por volumen y utilizar canales con énfasis en el precio.
    *   **Mensaje:** Resaltar el ahorro y la conveniencia. Ej: "Ahorre en sus compras diarias con nuestras ofertas exclusivas para familias."

*   **Clúster 0 (Familias con Adolescentes y Buenos Ingresos):**
    *   **Marketing:** Ofertas que apelen a toda la familia, productos de conveniencia, o promociones relacionadas con eventos familiares. Podría explorarse el marketing dirigido a los intereses de los adolescentes.
    *   **Mensaje:** Enfocarse en la facilidad y el disfrute familiar. Ej: "Disfrute de la cena en familia con nuestra selección de productos frescos y listos para cocinar."

**2. Prevención de la Fuga de Clientes (Churn Prevention):**

*   **Identificación de Riesgo:** Los clústeres con bajo gasto y bajos ingresos (como el 1, 3 y 5) son más propensos a la fuga por motivos de precio. Su comportamiento debe ser monitoreado de cerca.

*   **Anomalías (Outliers):** Los clientes identificados con un alto `Quantization_Error` (anomalías) podrían ser clientes insatisfechos o con necesidades muy específicas. Representan una oportunidad para una intervención personalizada para entender y resolver sus problemas.

*   **Estrategias Proactivas:**
    *   **Para Clústeres de Bajo Riesgo/Sensibles al Precio:** Ofrecer incentivos personalizados como descuentos exclusivos, programas de puntos o encuestas de satisfacción dirigidas a entender y mejorar su experiencia antes de que consideren irse.
    *   **Para Clientes de Alto Valor (Clúster 2 y 4):** Si se detecta una disminución en su actividad, contactar proactivamente con ofertas de valor añadido (servicios premium, acceso a preventas, gestores de cuenta).

*   **Comunicación Personalizada para Retención:** Adaptar el tono y el contenido de los mensajes de retención a las características específicas de cada clúster, abordando sus preocupaciones o necesidades más relevantes.

En resumen, la segmentación permite una aproximación mucho más precisa y efectiva en todas las estrategias de interacción con el cliente, optimizando el retorno de la inversión en marketing y mejorando la retención.

**PRODUCTOS DE ORO** NICHO CLUSTER 5


Vamos a analizar el comportamiento de MntGoldProds (Monto gastado en productos de oro) a través de los clústeres:

Basándonos en las características promedio de cada clúster, podemos observar lo siguiente sobre el gasto en productos de oro:

Clúster 2 (Clientes de Alto Valor y sin Dependientes): Este clúster muestra un gasto en MntGoldProds significativamente alto (un valor normalizado positivo), lo cual es coherente con su perfil de alto valor y altos ingresos. Es probable que estos clientes no solo gasten en otros productos, sino que también tengan la capacidad y el deseo de adquirir artículos de lujo como productos de oro.

Clúster 4 (Jóvenes con Altos Ingresos y Consumo Elegante): Similar al Clúster 2, este grupo también presenta un gasto por encima del promedio en MntGoldProds, lo que refuerza su imagen de clientes con poder adquisitivo y gustos por productos de mayor valor. Su 'consumo elegante' se extiende a estos artículos.

Clúster 5 (Mayores con Niños Pequeños y Bajos Ingresos): Este clúster muestra un gasto en MntGoldProds ligeramente por encima del promedio (o muy cercano al promedio), a pesar de tener bajos ingresos. Esto podría indicar que, aunque su presupuesto es limitado, tienen una propensión a gastar en 'productos gold' que podrían ser regalos, artículos especiales o inversiones pequeñas. Sin embargo, su gasto en otras categorías es generalmente bajo.

Clúster 0 (Familias con Adolescentes y Buenos Ingresos): El gasto en MntGoldProds en este clúster es cercano al promedio. Esto sugiere que no es una categoría de gasto prioritaria para ellos, aunque tienen ingresos por encima del promedio. Su gasto se distribuye más en otras categorías o en necesidades relacionadas con la familia.

Clúster 1 y Clúster 3 (Familias Jóvenes con Bajo Presupuesto y Mayores Sensibles al Precio): Estos clústeres muestran un gasto en MntGoldProds por debajo del promedio. Esto es consistente con sus perfiles de bajo ingreso y sensibilidad al precio, donde los productos de oro no son una prioridad en sus presupuestos ajustados.

En resumen, el gasto en MntGoldProds es un buen indicador del poder adquisitivo y de la preferencia por artículos de lujo o regalos, destacando a los clústeres de alto valor (2 y 4) y mostrando un patrón interesante en el Clúster 5, que a pesar de sus ingresos limitados, mantiene un cierto nivel de gasto en esta categoría.
Según el análisis que hemos realizado, una campaña de ese tipo podría ser viable pero solo si se dirige específicamente al Clúster 5 (Mayores con Niños Pequeños y Bajos Ingresos).

Aunque este clúster tiene ingresos bajos, se observó que su gasto en MntGoldProds está ligeramente por encima o muy cerca del promedio general. Esto sugiere que, a pesar de las limitaciones presupuestarias, tienen una propensión a adquirir artículos de oro, posiblemente para regalos, ocasiones especiales o como pequeñas inversiones.

Vamos a analizar el Clúster 5 (Mayores con Niños Pequeños y Bajos Ingresos):

Características Clave:

Edad: Este es el grupo de clientes más mayores.
Ingresos: Sus ingresos están por debajo del promedio.
Hogares: Tienen una alta presencia de niños pequeños, pero menos adolescentes.
Gasto General: Su gasto en la mayoría de los productos es bajo.
Gasto en 'MntGoldProds': A pesar de sus bajos ingresos, muestran un gasto en productos de oro ligeramente por encima o muy cerca del promedio. Esto es un punto interesante que sugiere que, aunque su presupuesto es limitado, tienen una propensión específica hacia esta categoría, quizás para regalos o artículos especiales.
En resumen, el Clúster 5 representa a clientes de edad avanzada, con ingresos por debajo del promedio, que tienen niños pequeños en casa y un gasto general bajo, pero con una particularidad en su consumo de productos de oro.

### Estrategias para Venta de Productos Bancarios por Clúster

Aquí se detallan las medidas a tomar para cada clúster identificado, con el objetivo de vender productos bancarios de manera efectiva:

### Clúster 0: Familias con Adolescentes y Buenos Ingresos
*   **Descripción del Perfil:** Padres con hijos adolescentes, ingresos estables y consumo moderado.
*   **Productos Sugeridos:** Cuentas de ahorro para educación universitaria, préstamos hipotecarios para mejoras del hogar, tarjetas de crédito con recompensas (cashback o viajes) que beneficien a la familia, seguros de vida y hogar, planes de inversión a medio plazo.
*   **Estrategia de Marketing:** Enfocarse en la seguridad financiera familiar, la planificación a futuro y el disfrute de beneficios. Campañas sobre cómo el banco puede apoyar sus metas educativas y patrimoniales. Promoción de servicios de banca en línea eficientes para personas ocupadas.

### Clúster 1: Familias Jóvenes con Bajo Presupuesto
*   **Descripción del Perfil:** Familias jóvenes con muchos dependientes y recursos limitados.
*   **Productos Sugeridos:** Cuentas de ahorro con bajas comisiones, microcréditos o préstamos personales pequeños y flexibles para emergencias, productos para construir historial crediticio, herramientas de presupuesto y finanzas personales (apps bancarias).
*   **Estrategia de Marketing:** Mensajes centrados en la ayuda para la estabilidad financiera, el control de gastos y la construcción de un futuro. Ofrecer asesoramiento gratuito sobre finanzas básicas. Destacar la facilidad de acceso y el apoyo en momentos difíciles.

### Clúster 2: Clientes de Alto Valor y sin Dependientes
*   **Descripción del Perfil:** Segmento de alto valor, clientes mayores con ingresos muy altos y sin dependientes.
*   **Productos Sugeridos:** Servicios de banca privada, gestión patrimonial avanzada, fondos de inversión de alto rendimiento y diversificados, planes de sucesión y herencia, tarjetas de crédito premium con beneficios exclusivos (conserjería, accesos VIP).
*   **Estrategia de Marketing:** Comunicación muy personalizada y discreta a través de gestores de cuenta. Invitaciones a eventos exclusivos de inversión. Enfatizar la exclusividad, el servicio personalizado y la optimización de su patrimonio.

### Clúster 3: Familias Mayores Sensibles al Precio
*   **Descripción del Perfil:** Clientes mayores con bajos ingresos y niños pequeños, muy sensibles a los precios.
*   **Productos Sugeridos:** Cuentas de ahorro con rendimientos competitivos pero sin riesgos, planes de ahorro a corto plazo, productos de inversión básicos y seguros (por ejemplo, depósitos a plazo fijo), seguros de salud y asistencia.
*   **Estrategia de Marketing:** Comunicación clara y transparente sobre costos y beneficios. Enfocarse en la seguridad, la simplicidad y la protección de sus ahorros. Promocionar ofertas especiales para la tercera edad y facilidades para la banca presencial.

### Clúster 4: Jóvenes con Altos Ingresos y Consumo Elegante
*   **Descripción del Perfil:** Clientes jóvenes con altos ingresos y sin dependientes, alto gasto, posiblemente prefieren canales de compra físicos.
*   **Productos Sugeridos:** Soluciones de inversión flexibles y digitales, préstamos para vehículos de lujo o bienes raíces selectos, tarjetas de crédito con programas de recompensas de alto nivel (viajes, experiencias), cuentas de ahorro de alto interés.
*   **Estrategia de Marketing:** Destacar la conveniencia, la modernidad y la capacidad de maximizar sus experiencias de vida. Aunque prefieren menos web, una experiencia móvil robusta es clave, junto con gestores de cuenta accesibles para consultas específicas.

### Clúster 5: Mayores con Niños Pequeños y Bajos Ingresos
*   **Descripción del Perfil:** Clientes de edad avanzada, con ingresos por debajo del promedio y niños pequeños en casa, con un gasto general bajo, pero con una particularidad en su consumo de productos de oro.
*   **Productos Sugeridos:** Cuentas de ahorro para nietos o dependientes jóvenes, seguros de vida con planes de legado, productos de inversión conservadores (como fondos garantizados), asesoramiento sobre planificación financiera para asegurar el futuro de los niños a su cargo. Podrían estar interesados en productos que les permitan ahorrar pequeñas cantidades de oro físico o inversiones en metales preciosos si esta es su inclinación.
*   **Estrategia de Marketing:** Mensajes enfocados en el legado, la protección de los seres queridos y el apoyo a las futuras generaciones. Ofrecer asesoramiento comprensivo y opciones de productos que combinen seguridad con un impacto a largo plazo para sus dependientes. Dada su propensión a 'productos gold', se podría explorar cómo el banco puede ofrecer opciones seguras y accesibles en esa línea.

## Informe Ejecutivo: Segmentación de Clientes y Detección de Anomalías con Self-Organizing Maps (SOM)

### 1. Introducción y Objetivos

Este informe detalla un análisis de segmentación de clientes realizado con el objetivo de identificar grupos de clientes con características y comportamientos similares, así como detectar clientes atípicos o anomalías. El objetivo principal es proporcionar insights accionables para la personalización de estrategias de marketing y la optimización de la prevención de fuga de clientes.

### 2. Preprocesamiento de Datos

Los datos iniciales de la campaña de marketing fueron sometidos a un proceso de limpieza y transformación. Esto incluyó:
*   Manejo de valores faltantes en la columna 'Income', los cuales fueron imputados con la mediana.
*   Normalización de variables numéricas para escalar los datos y asegurar que ningún atributo dominara el proceso de clustering.
*   Codificación One-Hot de variables categóricas ('Education', 'Marital_Status') para convertirlas en un formato numérico adecuado para los algoritmos.

### 3. Aplicación de Self-Organizing Maps (SOM)

Para la segmentación, se utilizó un Self-Organizing Map (SOM), una red neuronal no supervisada que reduce la dimensionalidad y visualiza estructuras de clústeres. Se entrenó un SOM de 10x10 neuronas utilizando las características preprocesadas del cliente. La U-matrix y los planos de componentes (como se visualizó en las secciones anteriores) revelaron:
*   **U-matrix:** Las áreas oscuras indicaron la presencia de clústeres, mientras que las áreas claras delinearon las fronteras entre ellos.
*   **Planos de Componentes:** Mostraron cómo características individuales como 'Income', 'MntWines', 'Kidhome', entre otras, se distribuyen a lo largo del mapa, ayudando a entender el perfil de cada región.

### 4. Segmentación de Clientes

Se aplicó el algoritmo K-Means a los pesos de las neuronas del SOM para identificar **6 clústeres distintos** de clientes. Cada cliente del dataset original fue asignado al clúster de su neurona ganadora (BMU).

Los 6 segmentos identificados, con su tamaño y características principales, son:

*   **Clúster 0 (402 clientes): Familias con Adolescentes y Buenos Ingresos**
    *   _Perfil:_ Padres con hijos adolescentes, ingresos estables y consumo moderado.
*   **Clúster 1 (417 clientes): Familias Jóvenes con Bajo Presupuesto**
    *   _Perfil:_ Familias jóvenes con muchos dependientes y recursos limitados, bajo gasto general.
*   **Clúster 2 (284 clientes): Clientes de Alto Valor y sin Dependientes**
    *   _Perfil:_ Segmento de alto valor, clientes mayores con ingresos muy altos y sin dependientes, gasto muy alto en todas las categorías.
*   **Clúster 3 (671 clientes): Familias Mayores Sensibles al Precio**
    *   _Perfil:_ Clientes mayores con bajos ingresos y niños pequeños, muy sensibles a los precios, gasto muy bajo.
*   **Clúster 4 (296 clientes): Jóvenes con Altos Ingresos y Consumo Elegante**
    *   _Perfil:_ Clientes jóvenes con altos ingresos y sin dependientes, alto gasto, posiblemente prefieren canales de compra físicos.
*   **Clúster 5 (170 clientes): Mayores con Niños Pequeños y Bajos Ingresos**
    *   _Perfil:_ Clientes de edad avanzada, con ingresos por debajo del promedio y niños pequeños en casa, gasto general bajo pero con una propensión notable al consumo de productos de oro.

### 5. Detección de Anomalías

Se identificaron anomalías utilizando el **error de cuantificación** del SOM. Clientes con un error de cuantificación superior al 99º percentil fueron marcados como anómalos. Se detectaron **23 anomalías**, que representan clientes con características muy distintas a los patrones principales del dataset, lo que sugiere que podrían ser clientes insatisfechos, con necesidades muy específicas o errores en los datos. Estos clientes requieren una revisión individualizada.

### 6. Estrategias de Marketing y Prevención de Fuga

La segmentación permite la creación de estrategias personalizadas:

*   **Campañas de Marketing Personalizadas:** Adaptar ofertas y mensajes a cada clúster (productos premium para Clúster 2 y 4, descuentos para Clúster 1, 3 y 5, ofertas familiares para Clúster 0).
*   **Prevención de Fuga:** Monitorear clústeres de bajo gasto (1, 3, 5) y anomalías. Implementar estrategias proactivas como incentivos personalizados o contacto directo en caso de disminución de actividad, especialmente para clientes de alto valor (2 y 4).

### 7. Conclusiones y Próximos Pasos

La segmentación de clientes mediante SOM ha proporcionado una comprensión profunda de la base de clientes, permitiendo la identificación de 6 perfiles distintos y un grupo de anomalías. Esta información es crucial para la toma de decisiones estratégicas, desde el desarrollo de productos hasta la asignación de recursos de marketing y la mejora de la retención de clientes.

**Próximos Pasos:**
*   Profundizar en el análisis de las anomalías para entender sus causas.
*   Diseñar y probar campañas de marketing específicas para cada clúster.
*   Implementar un sistema de monitoreo continuo para el comportamiento de los clústeres y la detección temprana de posibles fugas.
"""